---
- hosts: rabbitmq
  user: root
  gather_facts: yes
  tasks:
    - name: debug1
      debug:
        #msg: "{{groups['rabbitmq_main'][0]}}"
        msg: " {{ hostvars[groups['rabbitmq_main'][0]].hostname }} "

    - name: debug2
      debug:
        msg: "{{ ansible_facts.['devices'] | dict2items }}"
      when: "'sdb' in ( ansible_facts['devices'] | list )"
