---
- hosts: all
  user: root
  gather_facts: no
  tasks:
    - name: useradd or passwd
      user:
        name: "{{ user }}"
        password: "{{ password | password_hash('sha512') }}"
        state: present

    - name: set sudo to new_user
      lineinfile:
        path: /etc/sudoers.d/{{ user }}
        line: "{{ user }} ALL=(ALL) NOPASSWD:ALL"
        create: yes
      when:
        - sudo is defined
        - sudo == "yes"
