---
# tasks file for zabbix_yum
- name: install zabbix-agent
  yum:
    name: http://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-agent-5.0.2-1.el7.x86_64.rpm
    state: present

- name: replace string in /etc/zabbix/zabbix_agentd.conf
  replace:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: "=127.0.0.1$"
    replace: "={{groups['zabbix_proxy'][0]}}"

- name: replace string in /etc/zabbix/zabbix_agentd.conf
  replace:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: "=Zabbix server$"
    replace: "={{hostname}}"

- name: enable and start zabbix-agent
  systemd:
    name: zabbix-agent
    state: started
    enabled: yes
